{["irc_server/src/*","irc_server/tests/*"], [debug_info, {outdir, "irc_server/ebin"}]}.
{["tcp_listener/src/*","tcp_listener/tests/*"], [debug_info, {outdir, "tcp_listener/ebin"}]}.
{["process_registry/src/*","process_registry/tests/*"], [debug_info, {outdir, "process_registry/ebin"}]}.